name: Auto Assign

on:
  pull_request:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ohnogumi/assign-reviewers@v0.0.5
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
