name: Test

on:
  schedule:
    # Every 1 hour
    - cron: "0 * * * *"

  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  archive:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-linux-x64.zip"

      - run: bun i -f

      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(jq '.dependencies["playwright"]' package.json -r)" >> $GITHUB_ENV

      - name: Cache Playwright Browsers
        id: cache-playwright-browsers
        uses: actions/cache@main
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright with dependencies
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: bun playwright install chromium

      - run: bun run test
        env:
          YOUTUBE_DATA_API_KEY: ${{ secrets.YOUTUBE_DATA_API_KEY }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
